/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/usr/bin/python3: can't open file '/content/drive/MyDrive/HiCMAE/scripts/voxceleb2/audio_visual/hicmae_pretrain_base/cream-d/run_class_finetuning_av.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/content/drive/MyDrive/HiCMAE/scripts/voxceleb2/audio_visual/hicmae_pretrain_base/cream-d/run_class_finetuning_av.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/content/drive/MyDrive/HiCMAE/scripts/voxceleb2/audio_visual/hicmae_pretrain_base/cream-d/run_class_finetuning_av.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file '/content/drive/MyDrive/HiCMAE/scripts/voxceleb2/audio_visual/hicmae_pretrain_base/cream-d/run_class_finetuning_av.py': [Errno 2] No such file or directory
[2024-03-25 07:04:51,348] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 659) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_class_finetuning_av.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-25_07:04:51
  host      : 46303d576206
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 660)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-03-25_07:04:51
  host      : 46303d576206
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 661)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-03-25_07:04:51
  host      : 46303d576206
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 662)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-25_07:04:51
  host      : 46303d576206
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 659)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
